### ISSUE TITLE
vagrant up failed on Windows 7 x64

### ISSUE THREAD

**Issue by barbushin** [viccherubini/expert-php-deployments#1]
Hi

I have buy "Expert PHP Deployments" book and executed `vagrant up` for your Vagrantfile from this repository on Windows 7 x64 with VirtualBox 4.2.18 and Vagrant 1.3.5.

And it failed in some of final stages. See console log:

D:\server\home\localhost\www\vagrant>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Box 'precise64' was not found. Fetching box from specified URL for
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading or copying the box...
Extracting box...ate: 733k/s, Estimated time remaining: --:--:--)
Successfully added box 'precise64' with provider 'virtualbox'!
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 8000 => 8000 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

Can you please tell me what I'm doing wrong?
Thank you!

**Comment by barbushin** [comment]
I also tried it on VirtualBox 2.3.6 and result was the same :(

**Comment by viccherubini** [comment]
Thanks for reporting this. When I'm around a computer with Win7x64 I'll take a look and see what I can find out.

**Comment by barbushin** [comment]
I have fixed in changing `Vagrantfile`

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
    v.customize ["modifyvm", :id, "--cpus", "1"]
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    v.customize ["modifyvm", :id, "--hwvirtex", "off"]
  end

**Comment by barbushin** [comment]
May be you should also change it in your file :)

**Comment by viccherubini** [comment]
Thanks for doing the research on this. I do mention in the book that you should adjust the settings accordingly (page 12).

**Comment by barbushin** [comment]
I think it's just better to provide more universal configuration in the book. It will save a lot of time for users that will try to understand what is wrong with your config.
